apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels: { app: task-tracker }
  template:
    metadata:
      labels: { app: task-tracker }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: app
          image: YOUR_DOCKERHUB_USERNAME/task-tracker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_URL } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db-secret, key: DB_USER } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASS } }
          ports:
            - containerPort: 8080