apiVersion: v1
kind: Service
metadata:
  name: task-tracker
  namespace: lab
spec:
  type: NodePort
  selector: { app: task-tracker }
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080